stages:
  - build
  - tests
  - cleanup

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose build
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

rubocop:
  stage: tests
  script:
    - docker-compose run rubocop

rspec:
  stage: tests
  script:
    - docker-compose run rspec

cleanup:
  stage: cleanup
  script:
    - docker system prune -af && docker volume prune -f
